# DELETE FROM mgg.group;
# DELETE FROM mgg.groupcontacts;
# DELETE FROM mgg.discussion;
# DELETE FROM mgg.invite;
# DELETE FROM mgg.meeting;
# DELETE FROM mgg.meetingusers;
# DELETE FROM mgg.message;
# DELETE FROM mgg.contact;
# DELETE FROM mgg.notification;
# DELETE FROM mgg.discussionusers;

# Tests Values
@baseUrl =http://127.0.0.1:8000


@email = resttest@demo.com
@password = resttest123]
@firstname = rest
@lastname = test
@country = MA

@emailY = resttestY@demo.com
@passwordY = resttest123]Y
@firstnameY = restY
@lastnameY = testY
@countryY = FR

@groupTitle = My X Group
@contactTitle = Jhon X

@fakeuuid = 188ac66b-dff8-491e-b174-9f5e478d5a85

#------------------------------------------------------------
### 
# @name Register
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "firstname":"{{firstname}}",
    "lastname":"{{lastname}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "cpassword": "{{password}}",
    "country": "{{country}}",
    "agree": true
}

#------------------------------------------------------------
### 
# @name RegisterY
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "firstname":"{{firstnameY}}",
    "lastname":"{{lastnameY}}",
    "email": "{{emailY}}",
    "password": "{{passwordY}}",
    "cpassword": "{{passwordY}}",
    "country": "{{countryY}}",
    "agree": true
}

#------------------------------------------------------------
###
# @name Login
@authToken = {{Login.response.body.$.session.token}}
@userId = {{Login.response.body.$.session.id}}

POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

#------------------------------------------------------------
###
# @name LoginY
@authTokenY = {{LoginY.response.body.$.session.token}}
@userIdY = {{LoginY.response.body.$.session.id}}

POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "{{emailY}}",
    "password": "{{passwordY}}"
}



### -----------------------------------------------------------------------
#
#
#   Group API
#
#
### -----------------------------------------------------------------------



#------------------------------------------------------------
###
# @name newGroup

POST {{baseUrl}}/group/new HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "{{groupTitle}}"
}


#------------------------------------------------------------
###
# @name getMyGroups
@groupid = {{getMyGroups.response.body.$.rows[0].id}}

GET {{baseUrl}}/group/my HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

#------------------------------------------------------------
###
# @name getOneGroup

GET {{baseUrl}}/group/{{groupid}} HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

#------------------------------------------------------------
###
# @name updateGroup
@groupOneId = {{getOneGroup.response.body.$.row.id}}

POST {{baseUrl}}/group/{{groupOneId}}/update HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Updated {{groupTitle}}"
}

#------------------------------------------------------------
###
# @name updateFakeGroup

POST {{baseUrl}}/group/{{fakeuuid}}/update HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Update fake title"
}

#------------------------------------------------------------
###
# @name deleteFakeGroup

POST {{baseUrl}}/group/{{fakeuuid}}/delete HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

#------------------------------------------------------------
###
# @name deleteGroup

POST {{baseUrl}}/group/{{groupOneId}}/delete HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### -----------------------------------------------------------------------
#
#
#   Contact API
#
#
### -----------------------------------------------------------------------


#------------------------------------------------------------
###
# @name newContact

POST {{baseUrl}}/contact/new HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "{{contactTitle}}",
    "target_id": "{{userIdY}}"
}


#------------------------------------------------------------
###
# @name getMyContacts
@contactid = {{getMyContacts.response.body.$.rows[0].target_id}}

GET {{baseUrl}}/contact/my HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

#------------------------------------------------------------
###
# @name getOneContact

GET {{baseUrl}}/contact/{{contactid}} HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

#------------------------------------------------------------
###
# @name updateContact

POST {{baseUrl}}/contact/{{contactid}}/update HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "Updated {{contactTitle}}"
}

#------------------------------------------------------------
###
# @name deleteContact

POST {{baseUrl}}/contact/{{contactid}}/delete HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

