# DELETE FROM mgg.group;
# DELETE FROM mgg.groupcontacts;
# DELETE FROM mgg.discussion;
# DELETE FROM mgg.invite;
# DELETE FROM mgg.meeting;
# DELETE FROM mgg.meetingusers;
# DELETE FROM mgg.message;
# DELETE FROM mgg.contact;
# DELETE FROM mgg.notification;
# DELETE FROM mgg.discussionusers;

# Tests Values
@baseUrl =http://127.0.0.1:8000


@email = resttest@demo.com
@password = resttest123]
@firstname = rest
@lastname = test
@country = MA

@grouptitle = "My X Group"

@fakeuuid = 188ac66b-dff8-491e-b174-9f5e478d5a85

#------------------------------------------------------------
### 
# @name Register
POST {{baseUrl}}/auth/register HTTP/1.1
content-type: application/json

{
    "firstname":"{{firstname}}",
    "lastname":"{{lastname}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "cpassword": "{{password}}",
    "country": "{{country}}",
    "agree": true
}

#------------------------------------------------------------
###
# @name Login
@authToken = {{Login.response.body.$.session.token}}
@userId = {{Login.response.body.$.session.id}}

POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}


#------------------------------------------------------------
###
# @name newGroup

POST {{baseUrl}}/group/new HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "title":"{{grouptitle}}",
    "user_id":"{{userId}}"
}

#------------------------------------------------------------
###
# @name getMyGroups

GET {{baseUrl}}/group/my HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

#------------------------------------------------------------
###
# @name updateCompany
@company = {{getCompanies.response.body.$.data[0].company}}
@companyid = {{getCompanies.response.body.$.data[0].company.id}}

POST {{baseUrl}}/company/{{companyid}}/update HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "title" : "test Delivery",
    "description" : "Since 1999 we work with all type of clients",
    "country_id" :  "MA",
    "externalurl" : "https://safari.local/welcome",
    "firstname" : "Jhon",
    "lastname" : "Doe",
    "street" : "11 Pierre semard",
    "city" : "Charleville-Mezieres",
    "statename" : "Grand Est",
    "postal_code" : "08000",
    "agree" : true
}

#------------------------------------------------------------
###
# @name getCompanies


GET {{baseUrl}}/company/my HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

#------------------------------------------------------------
###
# @name getFakeUsers
GET {{baseUrl}}/company/{{fakeuuid}}/customers HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

#------------------------------------------------------------
###
@company = {{getCompanies.response.body.$.data[0].company}}
@companyid = {{getCompanies.response.body.$.data[0].company.id}}

# @name getUsers
GET {{baseUrl}}/company/{{companyid}}/users HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

#------------------------------------------------------------
###
@company = {{getCompanies.response.body.$.data[0].company}}
@companyid = {{getCompanies.response.body.$.data[0].company.id}}

# @name getManagers
GET {{baseUrl}}/company/{{companyid}}/managers HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

#------------------------------------------------------------
###
@company = {{getCompanies.response.body.$.data[0].company}}
@companyid = {{getCompanies.response.body.$.data[0].company.id}}

# @name getDrivers
GET {{baseUrl}}/company/{{companyid}}/drivers HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json

#------------------------------------------------------------
###
@company = {{getCompanies.response.body.$.data[0].company}}
@companyid = {{getCompanies.response.body.$.data[0].company.id}}

# @name getCustomers
GET {{baseUrl}}/company/{{companyid}}/customers HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/json