<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="/favicon.ico">
    <script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>
    <title>delivery</title>
    <link href="/css/app.b8406ff3.css" rel="preload" as="style">
    <link href="/js/app.f87f0faa.js" rel="preload" as="script">
    <link href="/js/chunk-vendors.77557ec0.js" rel="preload" as="script">
    <link href="/css/app.b8406ff3.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>" />
</head>

<body>
    <noscript><strong>We're sorry but delivery-app doesn't work properly without JavaScript enabled. Please enable it
            to continue.</strong></noscript>
    <div id="app"></div>
    <script src="<?php echo $this->url->get('js/chunk-vendors.77557ec0.js')?>"></script>
    <script src="<?php echo $this->url->get('js/app.f87f0faa.js')?>"></script>
</body>

</html>